import {defineField, defineType} from 'sanity'

const VENUE_SLUGS = [
  {title: 'Majorstua', value: 'majorstua'},
  {title: 'Solli', value: 'solli'},
  {title: 'Tønsberg', value: 'tonsberg'},
]

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Innstillinger',
  type: 'document',
  groups: [
    {name: 'contact', title: 'Kontakt', default: true},
    {name: 'packages', title: 'Selskap og pakker'},
    {name: 'story', title: 'Om Kverneriet'},
    {name: 'allergens', title: 'Allergener'},
  ],
  fields: [
    defineField({name: 'name', title: 'Navn', type: 'string', initialValue: 'Kverneriet', group: 'contact'}),
    defineField({name: 'legalName', title: 'Juridisk navn', type: 'string', group: 'contact'}),
    defineField({name: 'telephone', title: 'Telefon (E.164, f.eks. +4790600333)', type: 'string', group: 'contact'}),
    defineField({name: 'telephoneDisplay', title: 'Telefon slik det vises', type: 'string', group: 'contact'}),
    defineField({name: 'email', title: 'E-post (generell)', type: 'string', group: 'contact'}),
    defineField({name: 'giftcard', title: 'Gavekort-URL', type: 'url', group: 'contact'}),
    defineField({name: 'founded', title: 'Grunnlagt (år)', type: 'string', group: 'contact'}),
    defineField({
      name: 'sameAs',
      title: 'Sosiale profiler (Facebook, Instagram, TikTok, Google Business)',
      type: 'array',
      of: [{type: 'url'}],
      group: 'contact',
    }),
    defineField({name: 'priceRange', title: 'Prisnivå (tekst)', type: 'string', description: 'F.eks. «kr 84–369»', group: 'contact'}),
    defineField({name: 'deliveryMarkup', title: 'Påslag hjemlevering (tekst)', type: 'string', description: 'F.eks. «15–20 %»', group: 'contact'}),
    defineField({name: 'packagesNote', title: 'Regel for selskap', type: 'string', group: 'packages'}),
    defineField({name: 'packages', title: 'Matpakker', type: 'array', of: [{type: 'packageItem'}], group: 'packages'}),
    defineField({name: 'kidsPrice', title: 'Barnemeny ved selskap (kr)', type: 'number', group: 'packages'}),
    defineField({name: 'kidsNote', title: 'Merknad barnemeny', type: 'string', group: 'packages'}),
    defineField({name: 'brandStory', title: 'Kort om Kverneriet (brukes i søk og AI-svar)', type: 'localizedText', group: 'story'}),
    defineField({name: 'aboutTitle', title: 'Tittel på om-seksjonen (forsiden)', type: 'localizedString', group: 'story'}),
    defineField({name: 'about1', title: 'Om Kverneriet – avsnitt 1', type: 'localizedText', group: 'story'}),
    defineField({name: 'about2', title: 'Om Kverneriet – avsnitt 2', type: 'localizedText', group: 'story'}),
    defineField({
      name: 'allergenKey',
      title: 'Allergen-nøkkel (koder brukt i menyene)',
      type: 'array',
      of: [{type: 'allergenCode'}],
      group: 'allergens',
    }),
  ],
  preview: {prepare: () => ({title: 'Innstillinger'})},
})

export const venue = defineType({
  name: 'venue',
  title: 'Restaurant',
  type: 'document',
  groups: [
    {name: 'basic', title: 'Grunnlag', default: true},
    {name: 'hours', title: 'Åpningstider'},
    {name: 'booking', title: 'Booking og take-away'},
    {name: 'content', title: 'Tekst og bilder'},
  ],
  fields: [
    defineField({name: 'slug', title: 'Nøkkel', type: 'string', options: {list: VENUE_SLUGS}, validation: (r) => r.required(), group: 'basic', readOnly: true}),
    defineField({name: 'name', title: 'Kortnavn', type: 'string', validation: (r) => r.required(), group: 'basic'}),
    defineField({name: 'fullName', title: 'Fullt navn', type: 'string', validation: (r) => r.required(), group: 'basic'}),
    defineField({name: 'city', title: 'By', type: 'string', validation: (r) => r.required(), group: 'basic'}),
    defineField({name: 'area', title: 'Område', type: 'string', description: 'F.eks. Majorstuen, Solli plass, Kaldnes', group: 'basic'}),
    defineField({name: 'areaCues', title: 'Stedsord (for søk)', type: 'array', of: [{type: 'string'}], options: {layout: 'tags'}, group: 'basic'}),
    defineField({name: 'since', title: 'Åpnet (år)', type: 'string', group: 'basic'}),
    defineField({name: 'tagline', title: 'Tagline (engelsk merkevarelinje)', type: 'string', group: 'basic'}),
    defineField({
      name: 'address',
      title: 'Adresse',
      type: 'object',
      group: 'basic',
      fields: [
        defineField({name: 'street', title: 'Gate', type: 'string', validation: (r) => r.required()}),
        defineField({name: 'postalCode', title: 'Postnummer', type: 'string', validation: (r) => r.required()}),
        defineField({name: 'city', title: 'Poststed', type: 'string', validation: (r) => r.required()}),
      ],
    }),
    defineField({name: 'geo', title: 'Kartposisjon', type: 'geopoint', group: 'basic'}),
    defineField({
      name: 'maps',
      title: 'Kartlenker',
      type: 'object',
      group: 'basic',
      fields: [
        defineField({name: 'google', title: 'Google Maps', type: 'url'}),
        defineField({name: 'apple', title: 'Apple Maps', type: 'url'}),
      ],
    }),
    defineField({name: 'facebook', title: 'Facebook-side', type: 'url', group: 'basic'}),
    defineField({name: 'email', title: 'E-post', type: 'string', group: 'basic'}),
    defineField({name: 'kitchen', title: 'Kjøkkenet', type: 'array', of: [{type: 'kitchenHours'}], group: 'hours'}),
    defineField({name: 'bar', title: 'Baren stenger', type: 'array', of: [{type: 'barHours'}], group: 'hours'}),
    defineField({name: 'lunch', title: 'Lunsj (tekst)', type: 'string', description: 'F.eks. «tirsdag–fredag fra 11.00»', group: 'hours'}),
    defineField({name: 'zenchef', title: 'Zenchef restaurant-id', type: 'string', group: 'booking'}),
    defineField({name: 'groupThreshold', title: 'Online booking for inntil (personer)', type: 'number', group: 'booking'}),
    defineField({
      name: 'channels',
      title: 'Take-away-kanaler',
      type: 'object',
      group: 'booking',
      fields: [
        defineField({name: 'pickup', title: 'Hent selv (OrderX)', type: 'url'}),
        defineField({name: 'wolt', title: 'Wolt', type: 'url'}),
        defineField({name: 'foodora', title: 'Foodora', type: 'url'}),
      ],
    }),
    defineField({name: 'drinksPdf', title: 'Drikkemeny (PDF)', type: 'file', options: {accept: 'application/pdf'}, group: 'booking'}),
    defineField({name: 'kidsPdf', title: 'Barnemeny (PDF)', type: 'file', options: {accept: 'application/pdf'}, group: 'booking'}),
    defineField({name: 'heroImage', title: 'Toppbilde', type: 'photo', group: 'content'}),
    defineField({name: 'heroSub', title: 'Undertekst i toppen', type: 'localizedString', group: 'content'}),
    defineField({name: 'slogan', title: 'Slagord (engelsk)', type: 'string', group: 'content'}),
    defineField({name: 'about1', title: 'Om restauranten – avsnitt 1', type: 'localizedText', group: 'content'}),
    defineField({name: 'about2', title: 'Om restauranten – avsnitt 2', type: 'localizedText', group: 'content'}),
    defineField({name: 'aboutImage', title: 'Bilde ved om-teksten', type: 'photo', group: 'content'}),
    defineField({name: 'gallery', title: 'Galleri', type: 'array', of: [{type: 'photo'}], group: 'content'}),
    defineField({name: 'menuPhoto', title: 'Bilde på menysiden', type: 'photo', group: 'content'}),
  ],
  preview: {select: {title: 'fullName', subtitle: 'address.street', media: 'heroImage'}},
})

export const menu = defineType({
  name: 'menu',
  title: 'Meny',
  type: 'document',
  fields: [
    defineField({name: 'venue', title: 'Restaurant', type: 'reference', to: [{type: 'venue'}], validation: (r) => r.required()}),
    defineField({name: 'updated', title: 'Sist oppdatert', type: 'date'}),
    defineField({name: 'sections', title: 'Seksjoner', type: 'array', of: [{type: 'menuSection'}]}),
  ],
  preview: {select: {title: 'venue.fullName', sections: 'sections'}, prepare: ({title, sections}) => ({title: `Meny – ${title}`, subtitle: `${(sections || []).length} seksjoner`})},
})

export const pressItem = defineType({
  name: 'pressItem',
  title: 'Presseomtale',
  type: 'document',
  fields: [
    defineField({name: 'key', title: 'Nøkkel', type: 'slug', description: 'Kort id, f.eks. db_2020', validation: (r) => r.required()}),
    defineField({
      name: 'outlet',
      title: 'Avis',
      type: 'string',
      options: {
        list: [
          {title: 'Dagbladet', value: 'dagbladet'},
          {title: 'Finansavisen', value: 'finansavisen'},
          {title: 'VG / Godt.no', value: 'vg'},
          {title: 'Aftenposten', value: 'aftenposten'},
          {title: 'Dagens Næringsliv', value: 'dn'},
          {title: 'Dagsavisen', value: 'dagsavisen'},
          {title: 'Nettavisen', value: 'nettavisen'},
          {title: 'Tønsbergs Blad', value: 'tb'},
          {title: 'Mer av Oslo', value: 'meravoslo'},
          {title: 'Østlands-Posten', value: 'op'},
        ],
      },
      validation: (r) => r.required(),
    }),
    defineField({name: 'title', title: 'Tittel', type: 'string', validation: (r) => r.required()}),
    defineField({name: 'date', title: 'Dato', type: 'date', validation: (r) => r.required()}),
    defineField({name: 'url', title: 'Lenke til artikkelen', type: 'url', validation: (r) => r.required()}),
    defineField({name: 'rating', title: 'Terningkast', type: 'string', description: '«6/6», «21/25» eller tomt'}),
    defineField({name: 'quote', title: 'Sitat (ordrett)', type: 'text', rows: 3, validation: (r) => r.required()}),
    defineField({
      name: 'venue',
      title: 'Gjelder',
      type: 'string',
      options: {list: [...VENUE_SLUGS, {title: 'Generelt', value: 'generelt'}]},
      validation: (r) => r.required(),
    }),
    defineField({name: 'photo', title: 'Bilde på kortet', type: 'photo'}),
    defineField({name: 'featured', title: 'Vis på forsiden', type: 'boolean', initialValue: true}),
    defineField({name: 'order', title: 'Rekkefølge', type: 'number'}),
  ],
  orderings: [{title: 'Rekkefølge', name: 'order', by: [{field: 'order', direction: 'asc'}]}],
  preview: {select: {title: 'title', subtitle: 'outlet', media: 'photo'}},
})

export const faqItem = defineType({
  name: 'faqItem',
  title: 'Spørsmål og svar',
  type: 'document',
  fields: [
    defineField({
      name: 'page',
      title: 'Vises på',
      type: 'string',
      options: {
        list: [
          {title: 'Forsiden', value: 'index'},
          ...VENUE_SLUGS,
          {title: 'Take-away', value: 'takeaway'},
          {title: 'Lunsj', value: 'lunsj'},
          {title: 'Julebord', value: 'julebord'},
          {title: 'Selskap', value: 'selskap'},
          {title: 'Late night', value: 'late-night'},
        ],
      },
      validation: (r) => r.required(),
    }),
    defineField({name: 'question', title: 'Spørsmål', type: 'localizedString', validation: (r) => r.required()}),
    defineField({name: 'answer', title: 'Svar', type: 'localizedText', validation: (r) => r.required()}),
    defineField({name: 'order', title: 'Rekkefølge', type: 'number'}),
  ],
  preview: {select: {title: 'question.no', subtitle: 'page'}},
})

export const post = defineType({
  name: 'post',
  title: 'Blogginnlegg',
  type: 'document',
  fields: [
    defineField({name: 'title', title: 'Tittel', type: 'string', validation: (r) => r.required()}),
    defineField({name: 'slug', title: 'URL-navn', type: 'slug', options: {source: 'title', maxLength: 80}, validation: (r) => r.required()}),
    defineField({name: 'publishedAt', title: 'Publisert', type: 'datetime', validation: (r) => r.required()}),
    defineField({name: 'excerpt', title: 'Ingress', type: 'text', rows: 3, description: 'Vises i listen og i søkeresultater (maks 155 tegn)', validation: (r) => r.max(160)}),
    defineField({name: 'mainImage', title: 'Hovedbilde', type: 'photo'}),
    defineField({name: 'body', title: 'Innhold', type: 'richText', validation: (r) => r.required()}),
    defineField({name: 'author', title: 'Skrevet av', type: 'string'}),
    defineField({name: 'venue', title: 'Gjelder restaurant (valgfritt)', type: 'string', options: {list: VENUE_SLUGS}}),
    defineField({name: 'seoTitle', title: 'SEO-tittel (valgfritt, maks 60 tegn)', type: 'string', validation: (r) => r.max(60)}),
  ],
  orderings: [{title: 'Nyeste først', name: 'newest', by: [{field: 'publishedAt', direction: 'desc'}]}],
  preview: {select: {title: 'title', subtitle: 'publishedAt', media: 'mainImage'}},
})

export const landingPage = defineType({
  name: 'landingPage',
  title: 'Landingsside',
  type: 'document',
  fields: [
    defineField({
      name: 'slug',
      title: 'Side',
      type: 'string',
      options: {list: [{title: 'Lunsj', value: 'lunsj'}, {title: 'Julebord', value: 'julebord'}, {title: 'Selskap', value: 'selskap'}, {title: 'Late night', value: 'late-night'}]},
      validation: (r) => r.required(),
      readOnly: true,
    }),
    defineField({name: 'seoTitle', title: 'SEO-tittel (maks 60)', type: 'string', validation: (r) => r.max(60)}),
    defineField({name: 'seoDescription', title: 'SEO-beskrivelse (maks 155)', type: 'text', rows: 3, validation: (r) => r.max(155)}),
    defineField({name: 'eyebrow', title: 'Liten linje over tittelen', type: 'string'}),
    defineField({name: 'h1', title: 'Tittel', type: 'string'}),
    defineField({name: 'sub', title: 'Undertekst i toppen', type: 'text', rows: 2}),
    defineField({name: 'heroImage', title: 'Toppbilde', type: 'photo'}),
    defineField({name: 'sectionEyebrow', title: 'Liten linje over mellomtittel', type: 'string'}),
    defineField({name: 'h2', title: 'Mellomtittel', type: 'string'}),
    defineField({name: 'body', title: 'Brødtekst', type: 'richText'}),
    defineField({name: 'factsTitle', title: 'Tittel på faktakortet', type: 'string'}),
    defineField({name: 'facts', title: 'Faktapunkter', type: 'array', of: [{type: 'fact'}]}),
    defineField({name: 'factsNote', title: 'Merknad under faktakortet', type: 'string'}),
  ],
  preview: {select: {title: 'h1', subtitle: 'slug'}},
})
